### ISSUE TITLE
BUG: Goldy Bot still crashes when "raise_on_load_error" is set to false.

### ISSUE THREAD

**Issue by THEGOLDENPRO** [Goldy-Bot/Goldy-Bot-V5#14]
When `raise_on_load_error` is set to false goldy bot is meant to ignore the extension and continue loading other stuff but when the user forgets the `load()` function the command in the extension loads but the actual extension doesn't so it leads to this error below:

```python
[DEBUG] (Goldy Bot) - [Token] Searching current working directory for .env file if exists...
[DEBUG] (Goldy Bot) - [Token] Grabbing discord token...
[DEBUG] (Goldy Bot) - [Token] Grabbing database token...
[DEBUG] (Goldy Bot) - [Token] Done
[INFO] (Goldy Bot) - [Database] AsyncIOMotorClient Connected!
[DEBUG] (Goldy Bot) - [JSONConfig] Opening config file at './goldy.json'...
[DEBUG] (Goldy Bot) - [JSONConfig] Phrasing json in config to dict...
[DEBUG] (Goldy Bot) - [JSONConfig] Done!
[DEBUG] (Goldy Bot) - [Goldy] Nextcore shard manager connecting...
[DEBUG] (Goldy Bot) - [Goldy] Application data requested!
[DEBUG] (Goldy Bot) - [Database] [goldy_main] Found '{'_id': '863416692083916820'}' in 'guild_configs.'
[DEBUG] (Goldy Bot) - [Database] [goldy_main] Edited '{'_id': '863416692083916820'}' into '{'_id': '863416692083916820', 'code_name': 'test_server', 'prefix': '!', 'roles': {}, 'channels': {}, 'allowed_extensions': [], 'disallowed_extensions': [], 'hidden_extensions': []}.'
[INFO] (Goldy Bot) - [ExtensionLoader] Found extension folder at 'D:\test_goldybot\extensions'.
[DEBUG] (Goldy Bot) - [ExtensionLoader] Found the module 'test.py' in extensions.
[WARNING] (Goldy Bot) - [ExtensionLoader] Couldn't find extension path at 'D:\test_goldybot\env\Lib\site-packages\GoldyBot\internal_extensions'!
[DEBUG] (Goldy Bot) - [Command] [hello] Command initialized!
[DEBUG] (Goldy Bot) - [ExtensionLoader] Calling the 'load()' function in the extension at D:\test_goldybot\extensions\test.py...
[ERROR] (Goldy Bot) - [ExtensionLoader] We encountered an error while trying to load extension at 'D:\test_goldybot\extensions\test.py'! You most likely forgot the 'load()' function.
ERROR --> module 'D:\test_goldybot\extensions\test' has no attribute 'load'
Traceback (most recent call last):
  File "run.py", line 5, in <module>
    goldy.start() # Launch goldy bot.
  File "D:\test_goldybot\env\lib\site-packages\GoldyBot\goldy\__init__.py", line 96, in start
    self.async_loop.run_until_complete(
  File "C:\Users\jassi\AppData\Local\Programs\Python\Python38\lib\asyncio\base_events.py", line 616, in run_until_complete
    return future.result()
  File "D:\test_goldybot\env\lib\site-packages\GoldyBot\goldy\__init__.py", line 127, in __start_async
    await self.setup()
  File "D:\test_goldybot\env\lib\site-packages\GoldyBot\goldy\__init__.py", line 158, in setup
    await self.command_loader.load()
  File "D:\test_goldybot\env\lib\site-packages\GoldyBot\goldy\commands\loader.py", line 38, in load
    if command.extension.is_ignored == False:
  File "D:\test_goldybot\env\lib\site-packages\GoldyBot\goldy\commands\__init__.py", line 105, in extension
    return utils.cache_lookup(self.extension_name, extensions_cache)[1]
TypeError: 'NoneType' object is not subscriptable
```

Because the extension is not loaded when the command is loaded it cannot find the extension leading to this traceback.

**Comment by THEGOLDENPRO** [comment]
currently attempting to fix this in the branch at https://github.com/Goldy-Bot/Goldy-Bot-V5/tree/fix/raise-on-load-crash
