### ISSUE TITLE
Command system rewrite

### ISSUE THREAD

**Issue by THEGOLDENPRO** [Goldy-Bot/Goldy-Bot-V5#63]
Yes, I'm insane. As the title says, I'll be rewriting hundreds of lines from the command system.

Commands will have a complete restructure as I'm not happy with the current state of things.

**Comment by THEGOLDENPRO** [comment]
Okay first things I want to take care of:

- [ ] GoldPlatter types will be removed.
- [ ] Command class will become a hybrid abstract class.
- [ ] Slash commands and prefix commands will have their own class inheriting from Command class.

Here are some links I'm pinning as I'll need them later:

https://medium.com/cp-massive-programming/design-patterns-cheat-sheet-list-e9a55d82de5d

https://cheatography.com/sercand/cheat-sheets/python-design-patterns/

**Comment by THEGOLDENPRO** [comment]
Okay, now that I've taken a closer look into this I don't think it's possible to separate slash command and prefix command into their own classes. I really would like to find a way but right now it seems complicated.

**Comment by THEGOLDENPRO** [comment]
Actually, I'll try and look into it further and also the next step would be coming up with a way to instance subcommands in a way it acts nearly exactly like a normal command object so that it relies less on the parent command and we don't recreate that mess in Command.__invoke_sub_cmd() 💀💀💀.

**Comment by THEGOLDENPRO** [comment]
Okay we finally got the new command system working. Now what is next is sub commands which I have a good idea on how it should be implemented.

You have two choices as the developer to register sub commands:

- Create a group command with the GoldyBot.command() decorator with parameter group set to true -> ``group=True`` and then create a sub command with ``command_name.sub_command()``.

- Instance a variable at the top of the class with ``GoldyBot.GroupCommand()`` then do ``variable.sub_command()`` to create a sub command.

This fixes both issues I personally had with sub commands. You no longer have to create a command just to use sub commands and you can still use the old master command implementation with ``group=True``.

**Comment by THEGOLDENPRO** [comment]
What we do next:

- [ ] Sub command method.
- [ ] Group command.
- [ ] Fix reloading and unloading if broken.

**Comment by THEGOLDENPRO** [comment]
For the group command we should make it inherit from Command and just throw a dummy function in. We should also force the name parameter as the function will not have a name.

**Comment by THEGOLDENPRO** [comment]
> 

after I'm done with this it's cleaning up time:
- [ ] Move params_utils to their relevant slash command and prefix command classes.
- [ ] Remove old Command class.

**Comment by THEGOLDENPRO** [comment]
> What we do next:
> 
> * [x]  Sub command method.
> * [x]  Group command.
> * [ ]  Fix reloading and unloading if broken.
> * [ ]  Fix prefix sub commands.

after I'm done with this it's cleaning up time:
- [ ] Move params_utils to their relevant slash command and prefix command classes.
- [ ] Remove old Command class.

**Comment by THEGOLDENPRO** [comment]
reloading has been fixed >> https://github.com/Goldy-Bot/Goldy-Bot-V5/commit/68f2633058968953416dd14035fcae0acd7725c0

**Comment by THEGOLDENPRO** [comment]
SilverPlatter was added and message components were fixed >> https://github.com/Goldy-Bot/Goldy-Bot-V5/commit/063ffdf4273d233db0286ddf77f53f0b4cd28d1a

**Comment by THEGOLDENPRO** [comment]
Working on merging params_utils with command objects now

**Comment by THEGOLDENPRO** [comment]
> Working on merging params_utils with command objects now

done >> https://github.com/Goldy-Bot/Goldy-Bot-V5/commit/4ae2a38dfe58b0ace2d3e8acba95b56c8dea5e22

**Comment by THEGOLDENPRO** [comment]
I found a BUG with the new command system.

This happens after trying to run the `/goldy` **slash** command. (it's triggering a prefix command 🤔)
```python
[DEBUG] (Goldy Bot) - [Database] [goldy_main] Found '{'_id': '863416692083916820'}' in 'guild_configs.'
[DEBUG] (Goldy Bot) - [PrefixCommand] [goldy] Attempting to phrase invoke data into parameters...
Exception occured in event handler
Traceback (most recent call last):
  File "/home/goldy/Documents/Projects/Python/.goldy_bot/Goldy-Bot-V5/env/lib/python3.8/site-packages/nextcore/common/dispatcher.py", line 464, in _run_event_handler
    await maybe_coro(callback, *args)
  File "/home/goldy/Documents/Projects/Python/.goldy_bot/Goldy-Bot-V5/env/lib/python3.8/site-packages/nextcore/common/maybe_coro.py", line 69, in maybe_coro
    return await result
  File "../GoldyBot/goldy/commands/listener.py", line 68, in on_interaction
    await command[1].invoke(
  File "../GoldyBot/goldy/commands/prefix_command.py", line 61, in invoke
    params = self.__invoke_data_to_params(data)
  File "../GoldyBot/goldy/commands/prefix_command.py", line 95, in __invoke_data_to_params
    for arg in data["content"].split(" ")[1:]:
KeyError: 'content'
```
For some reason, it triggers the prefix command instead of the slash command.

Further logs show that the prefix command is being registered with the slash command id. This shouldn't be possible.
```python
[DEBUG] (Goldy Bot) - [CommandLoader] Slash command 'goldy' payload grabbed.
[DEBUG] (Goldy Bot) - [CommandLoader] Command 'goldy' loaded.
[DEBUG] (Goldy Bot) - [PrefixCommand] [goldy] 'goldy' has been registered with id 'goldy'!
[DEBUG] (Goldy Bot) - [CommandLoader] Command 'goldy' loaded.
[DEBUG] (Goldy Bot) - [CommandLoader] Slash command 'timestamp' payload grabbed.
[DEBUG] (Goldy Bot) - [CommandLoader] Command 'timestamp' loaded.
[DEBUG] (Goldy Bot) - [PrefixCommand] [timestamp] 'timestamp' has been registered with id 'timestamp'!
[DEBUG] (Goldy Bot) - [CommandLoader] Command 'timestamp' loaded.
[DEBUG] (Goldy Bot) - [CommandLoader] Slash command 'extensions' payload grabbed.
[DEBUG] (Goldy Bot) - [CommandLoader] Command 'extensions' loaded.
[DEBUG] (Goldy Bot) - [PrefixCommand] [extensions] 'extensions' has been registered with id 'extensions'!
[DEBUG] (Goldy Bot) - [CommandLoader] Command 'extensions' loaded.
[INFO] (Goldy Bot) - [Goldy] Nextcore shards are connected and READY!
[DEBUG] (Goldy Bot) - [SlashCommand] [test] 'test' has been registered with id '1126485978496905296'!
[DEBUG] (Goldy Bot) - [SlashCommand] [setup_tree] 'setup_tree' has been registered with id '1126485978496905297'!
[DEBUG] (Goldy Bot) - [PrefixCommand] [hello] 'hello' has been registered with id '1126485978496905298'!
[DEBUG] (Goldy Bot) - [SlashCommand] [bear] 'bear' has been registered with id '1126485978496905299'!
[DEBUG] (Goldy Bot) - [SlashCommand] [nuke] 'nuke' has been registered with id '1126485979012800532'!
[DEBUG] (Goldy Bot) - [SlashCommand] [game] 'game' has been registered with id '1126485979012800534'!
[DEBUG] (Goldy Bot) - [PrefixCommand] [hi] 'hi' has been registered with id '1126485979012800535'!
[DEBUG] (Goldy Bot) - [PrefixCommand] [test_database] 'test_database' has been registered with id '1126485979012800536'!
[DEBUG] (Goldy Bot) - [PrefixCommand] [test_extension] 'test_extension' has been registered with id '1126485979012800537'!
[DEBUG] (Goldy Bot) - [PrefixCommand] [test_args] 'test_args' has been registered with id '1126485979012800539'!
[DEBUG] (Goldy Bot) - [SlashCommand] [test_mention_striper_role] 'test_mention_striper_role' has been registered with id '1126485979486752889'!
[DEBUG] (Goldy Bot) - [SlashCommand] [test_mention_striper_channel] 'test_mention_striper_channel' has been registered with id '1126485979486752890'!
[DEBUG] (Goldy Bot) - [SlashCommand] [test_mention_striper_user] 'test_mention_striper_user' has been registered with id '1126485979486752891'!
[DEBUG] (Goldy Bot) - [SlashCommand] [test_attachment] 'test_attachment' has been registered with id '1126485979486752892'!
[DEBUG] (Goldy Bot) - [SlashCommand] [test_options] 'test_options' has been registered with id '1126485979486752893'!
[DEBUG] (Goldy Bot) - [PrefixCommand] [test_buttons] 'test_buttons' has been registered with id '1126485979486752894'!
[DEBUG] (Goldy Bot) - [PrefixCommand] [test_channels] 'test_channels' has been registered with id '1126485979486752895'!
[DEBUG] (Goldy Bot) - [PrefixCommand] [test_guilds] 'test_guilds' has been registered with id '1126485979486752896'!
[DEBUG] (Goldy Bot) - [PrefixCommand] [stop] 'stop' has been registered with id '1126485979486752898'!
[DEBUG] (Goldy Bot) - [PrefixCommand] [goldy] 'goldy' has been registered with id '1126286658359263234'!
```

**Comment by THEGOLDENPRO** [comment]
currently working on sub commands for prefix commands.

I've done some improvements to the front end exceptions.
![image](https://github.com/Goldy-Bot/Goldy-Bot-V5/assets/66202304/053450fb-c4c8-4597-b500-bcef51e8bedf)

**Comment by THEGOLDENPRO** [comment]
> currently working on sub commands for prefix commands.
> 
> I've done some improvements to the front end exceptions. ![image](https://user-images.githubusercontent.com/66202304/251848745-053450fb-c4c8-4597-b500-bcef51e8bedf.png)

done and finished polishing check list.
