### ISSUE TITLE
BUG in new command system!

### ISSUE THREAD

**Issue by THEGOLDENPRO** [Goldy-Bot/Goldy-Bot-V5#70]
I found a BUG with the new command system.

This happens after trying to run the `/goldy` **slash** command. (it's triggering a prefix command 🤔)
```python
[DEBUG] (Goldy Bot) - [Database] [goldy_main] Found '{'_id': '863416692083916820'}' in 'guild_configs.'
[DEBUG] (Goldy Bot) - [PrefixCommand] [goldy] Attempting to phrase invoke data into parameters...
Exception occured in event handler
Traceback (most recent call last):
  File "/home/goldy/Documents/Projects/Python/.goldy_bot/Goldy-Bot-V5/env/lib/python3.8/site-packages/nextcore/common/dispatcher.py", line 464, in _run_event_handler
    await maybe_coro(callback, *args)
  File "/home/goldy/Documents/Projects/Python/.goldy_bot/Goldy-Bot-V5/env/lib/python3.8/site-packages/nextcore/common/maybe_coro.py", line 69, in maybe_coro
    return await result
  File "../GoldyBot/goldy/commands/listener.py", line 68, in on_interaction
    await command[1].invoke(
  File "../GoldyBot/goldy/commands/prefix_command.py", line 61, in invoke
    params = self.__invoke_data_to_params(data)
  File "../GoldyBot/goldy/commands/prefix_command.py", line 95, in __invoke_data_to_params
    for arg in data["content"].split(" ")[1:]:
KeyError: 'content'
```
For some reason, it triggers the prefix command instead of the slash command.

Further logs show that the prefix command is being registered with the slash command id. This shouldn't be possible.
```python
[DEBUG] (Goldy Bot) - [CommandLoader] Slash command 'goldy' payload grabbed.
[DEBUG] (Goldy Bot) - [CommandLoader] Command 'goldy' loaded.
[DEBUG] (Goldy Bot) - [PrefixCommand] [goldy] 'goldy' has been registered with id 'goldy'!
[DEBUG] (Goldy Bot) - [CommandLoader] Command 'goldy' loaded.
[DEBUG] (Goldy Bot) - [CommandLoader] Slash command 'timestamp' payload grabbed.
[DEBUG] (Goldy Bot) - [CommandLoader] Command 'timestamp' loaded.
[DEBUG] (Goldy Bot) - [PrefixCommand] [timestamp] 'timestamp' has been registered with id 'timestamp'!
[DEBUG] (Goldy Bot) - [CommandLoader] Command 'timestamp' loaded.
[DEBUG] (Goldy Bot) - [CommandLoader] Slash command 'extensions' payload grabbed.
[DEBUG] (Goldy Bot) - [CommandLoader] Command 'extensions' loaded.
[DEBUG] (Goldy Bot) - [PrefixCommand] [extensions] 'extensions' has been registered with id 'extensions'!
[DEBUG] (Goldy Bot) - [CommandLoader] Command 'extensions' loaded.
[INFO] (Goldy Bot) - [Goldy] Nextcore shards are connected and READY!
[DEBUG] (Goldy Bot) - [SlashCommand] [test] 'test' has been registered with id '1126485978496905296'!
[DEBUG] (Goldy Bot) - [SlashCommand] [setup_tree] 'setup_tree' has been registered with id '1126485978496905297'!
[DEBUG] (Goldy Bot) - [PrefixCommand] [hello] 'hello' has been registered with id '1126485978496905298'!
[DEBUG] (Goldy Bot) - [SlashCommand] [bear] 'bear' has been registered with id '1126485978496905299'!
[DEBUG] (Goldy Bot) - [SlashCommand] [nuke] 'nuke' has been registered with id '1126485979012800532'!
[DEBUG] (Goldy Bot) - [SlashCommand] [game] 'game' has been registered with id '1126485979012800534'!
[DEBUG] (Goldy Bot) - [PrefixCommand] [hi] 'hi' has been registered with id '1126485979012800535'!
[DEBUG] (Goldy Bot) - [PrefixCommand] [test_database] 'test_database' has been registered with id '1126485979012800536'!
[DEBUG] (Goldy Bot) - [PrefixCommand] [test_extension] 'test_extension' has been registered with id '1126485979012800537'!
[DEBUG] (Goldy Bot) - [PrefixCommand] [test_args] 'test_args' has been registered with id '1126485979012800539'!
[DEBUG] (Goldy Bot) - [SlashCommand] [test_mention_striper_role] 'test_mention_striper_role' has been registered with id '1126485979486752889'!
[DEBUG] (Goldy Bot) - [SlashCommand] [test_mention_striper_channel] 'test_mention_striper_channel' has been registered with id '1126485979486752890'!
[DEBUG] (Goldy Bot) - [SlashCommand] [test_mention_striper_user] 'test_mention_striper_user' has been registered with id '1126485979486752891'!
[DEBUG] (Goldy Bot) - [SlashCommand] [test_attachment] 'test_attachment' has been registered with id '1126485979486752892'!
[DEBUG] (Goldy Bot) - [SlashCommand] [test_options] 'test_options' has been registered with id '1126485979486752893'!
[DEBUG] (Goldy Bot) - [PrefixCommand] [test_buttons] 'test_buttons' has been registered with id '1126485979486752894'!
[DEBUG] (Goldy Bot) - [PrefixCommand] [test_channels] 'test_channels' has been registered with id '1126485979486752895'!
[DEBUG] (Goldy Bot) - [PrefixCommand] [test_guilds] 'test_guilds' has been registered with id '1126485979486752896'!
[DEBUG] (Goldy Bot) - [PrefixCommand] [stop] 'stop' has been registered with id '1126485979486752898'!
[DEBUG] (Goldy Bot) - [PrefixCommand] [goldy] 'goldy' has been registered with id '1126286658359263234'!
```

**Comment by THEGOLDENPRO** [comment]
has been fixed in >> https://github.com/Goldy-Bot/Goldy-Bot-V5/commit/1d99be2937d004f51bd0091952e9a517006e6969
