### ISSUE TITLE
BIG database bug in dev7

### ISSUE THREAD

**Issue by THEGOLDENPRO** [Goldy-Bot/Goldy-Bot-V5#95]
There's currently a bug in dev7's `.edit()` database method.

It's happening when find_one returns none here: https://github.com/Goldy-Bot/Goldy-Bot-V5/blob/212f0a1ffe0a532c7bdc060a11b3ace9237a887c/GoldyBot/goldy/database/databases/__init__.py#L30-L31

### Traceback
```python
[DEBUG] (Goldy Bot) - [Database] [goldy_main] Found '{'_id': '1016435541199294484'}' in 'guild_configs.'
[DEBUG] (Goldy Bot) - [SlashCommand] [timestamp] Attempting to phrase invoke data into parameters...
[DEBUG] (Goldy Bot) - [SlashCommand] [timestamp] Attempting to invoke command...
[DEBUG] (Goldy Bot) - [PermissionSystem] This command has no required perms. Your free! 🔓[INFO] (Goldy Bot) - [SlashCommand] [timestamp] Command invoked by 'emretech#0'.
[DEBUG] (Goldy Bot) - [SlashCommand] [timestamp] Calling sub command...
[DEBUG] (Goldy Bot) - [SlashCommand] [set_defaults] Attempting to phrase invoke data into parameters...
[DEBUG] (Goldy Bot) - [SlashCommand] [set_defaults] Found arg 'America/Los_Angeles'.
[DEBUG] (Goldy Bot) - [SlashCommand] [set_defaults] Found arg '0'.
[DEBUG] (Goldy Bot) - [SlashCommand] [set_defaults] Got args --> {'timezone': 'America/Los_Angeles', 'date_format': 0}
[DEBUG] (Goldy Bot) - [SlashCommand] [set_defaults] Attempting to invoke command...
[DEBUG] (Goldy Bot) - [PermissionSystem] This command has no required perms. Your free! 🔓[INFO] (Goldy Bot) - [SlashCommand] [set_defaults] Command invoked by 'emretech#0'.
[INFO] (Goldy Bot) - [Member] [emretech] [Database Wrapper] Pulling updated member data from database...
[DEBUG] (Goldy Bot) - [Member] [emretech] [Database Wrapper] Finding member's data collections...
[DEBUG] (Goldy Bot) - [Member] [emretech] [Database Wrapper] Found member's global data.
[DEBUG] (Goldy Bot) - [Member] [emretech] [Database Wrapper] Found member's guild data for 'nextcore_orx_Server'.
[INFO] (Goldy Bot) - [Member] [emretech] [Database Wrapper] Pushing data to the database...
[DEBUG] (Goldy Bot) - [Database] [goldy_member_data] '{'_id': '1'}' was not found in 'guild_configs.'
[ERROR] (Goldy Bot) - [SlashCommand] [set_defaults] Error occurred in the command 'set_defaults' executed by 'emretech#0'!
Exception occured in event handler
Traceback (most recent call last):
  File "/app/GoldyBot/goldy/commands/slash_command.py", line 77, in invoke
    return_value = await super().invoke(
  File "/app/GoldyBot/goldy/commands/command.py", line 179, in invoke
    return await lambda_func()
  File "/app/GoldyBot/internal_extensions/timestamps.py", line 172, in set_defaults
    await member_data.push(DatabaseEnums.MEMBER_GLOBAL_DATA, {"timezone": timezone, "datetime_formats": datetime_formats})
  File "/app/GoldyBot/goldy/database/wrappers/member.py", line 32, in push
    await database.edit(self.member.id, {"_id": doc_id}, data, overwrite = False)
  File "/app/GoldyBot/goldy/database/databases/__init__.py", line 31, in edit
    new_data = utils.update_dict(document_data, data) # Override the document's data with the new data.
  File "/app/GoldyBot/utils/_dict.py", line 7, in update_dict
    c = d1.copy()
AttributeError: 'NoneType' object has no attribute 'copy'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/nextcore/common/dispatcher.py", line 464, in _run_event_handler
    await maybe_coro(callback, *args)
  File "/usr/local/lib/python3.10/site-packages/nextcore/common/maybe_coro.py", line 69, in maybe_coro
    return await result
  File "/app/GoldyBot/goldy/commands/listener.py", line 75, in on_interaction
    await command[1].invoke(
  File "/app/GoldyBot/goldy/commands/slash_command.py", line 88, in invoke
    raise front_end_errors.UnknownError(platter, e, self.logger)
  File "/app/GoldyBot/goldy/nextcore_utils/front_end_errors.py", line 162, in __init__
    raise error
  File "/app/GoldyBot/goldy/commands/slash_command.py", line 85, in invoke
    await self.__invoke_sub_command(data, platter)
  File "/app/GoldyBot/goldy/commands/slash_command.py", line 150, in __invoke_sub_command
    await command.invoke(platter)
  File "/app/GoldyBot/goldy/commands/slash_command.py", line 88, in invoke
    raise front_end_errors.UnknownError(platter, e, self.logger)
GoldyBot.goldy.nextcore_utils.front_end_errors.UnknownError: Error occurred in the command 'set_defaults' executed by 'emretech#0'!
[DEBUG] (Goldy Bot) - [SlashCommand] [set_defaults] Interaction callback message was sent.
```

**Comment by THEGOLDENPRO** [comment]
fixed in dev8
